import type { Metadata } from 'next'
import { Fira_Code, Geist, Geist_Mono, Inter, Instrument_Serif } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const firaCode = Fira_Code({
  subsets: ['latin'],
  variable: '--font-fira-code',
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
  weight: ['400', '500', '600', '700', '800', '900'],
})

// インストゥルメントセリフフォントをGoogle Fontsから追加
const instrumentSerif = Instrument_Serif({
  subsets: ['latin'],
  variable: '--font-instrument-serif',
  display: 'swap',
  weight: '400',
})

// Inter Extra Boldを太字フォントとして使用
const interExtraBold = Inter({
  subsets: ['latin'],
  variable: '--font-sf-pro',
  display: 'swap',
  weight: ['800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${firaCode.variable} ${inter.variable} ${instrumentSerif.variable} ${interExtraBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
